mavlink/mavros

- mavros/launch/apm2_blacklist.yaml
As of ArduCopter 3.2, APM supports position and velocity setpoints via SET_POSITION_TARGET_LOCAL_NED.
> launch: enable setpoint plugins for APM

- mavros/launch/apm.launch
APM uses 1/1 (sys/comp) by default.
> launch: change apm target component id

- mavros/src/plugins/global_position.cpp
This fixes a crash in cases where a GLOBAL_POSITION_INT message
is received before a GPS_RAW_INT message, causing the `gps_fix`
pointer member to be dereferenced before it has been set.
I ran into this problem while testing mavros with APM on a mavlink channel that did not include GPS_RAW_INT messages: it was only transmitting LOCAL_POSITION_NED and GLOBAL_POSITION_INT. This configuration exposed an implicit dependency between the `gps` and `global_position` plugins, namely that the `global_position` plugin expects that the `gps` plugin has already received and processed a GPS_RAW_INT message beforehand, because it uses the latest `gps_fix` to determine relative altitude, heading, and covariance.
Because of that dependency, I suspect this isn't the *correct* fix for the crash, but it did …
> plugin: global_position: fix nullptr crash

- mavros/src/plugins/local_position.cpp
- mavros/src/plugins/setpoint_accel.cpp
- mavros/src/plugins/setpoint_position.cpp
- mavros/src/plugins/setpoint_velocity.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
- mavros_extras/src/plugins/visualization.cpp
For a desired position that is (1,5, 7) in ROS ENU, the must go forward 1 m which is X for both the ROS coordinate system and the PX4.  For y-axis, it is -5 m on the PX4 and the same for the z-axis.  I believe @mhkabir can verify this.  The frame issue #49 with two different frame conversions is due to keeping X as forward on the physical vehicle in ROS's coordinate system.  If we made Y forward, the IMU frames would be one conversion for body and inertial from NED to ENU thus being simpler to use.  However, this does break the ROS standards for coordinates.  @vooon Any insight?
> Changes some frames from world to body conversion for NED to ENU.

- mavros/CMakeLists.txt
- mavros/include/mavros/mavros_uas.h
- mavros/src/lib/uas_frame_conversions.cpp
- mavros/src/lib/uas_sensor_orientation.cpp
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/imu_pub.cpp
- mavros/src/plugins/local_position.cpp
- mavros/src/plugins/safety_area.cpp
- mavros/src/plugins/setpoint_accel.cpp
- mavros/src/plugins/setpoint_attitude.cpp
- mavros/src/plugins/setpoint_position.cpp
- mavros/src/plugins/setpoint_velocity.cpp
- mavros_extras/src/plugins/mocap_pose_estimate.cpp
- mavros_extras/src/plugins/px4flow.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
- mavros_extras/src/plugins/vision_speed_estimate.cpp
Finally, after some tinkering with @blackcoder, we were able to get to the proper conversions to position and orientation between ROS ENU and PX4 NED frames.
So, as this is a common code for many plugins, I decided to create a specific lib file where all the functions for frame conversions are installed. This functions are called by the plugins to do the conversions online.
**ADD:** This PR also updates some comments and doxygen documentation on plugins.
Right now, I think I'm just missing:
**Update:** Relative to covariance conversions, I'm still missing:
* Conversion to 7x7 full pose covariance matrix (attitude in quaternions instead of RPY)
* Conversion to quaternion covariance only (based on the previous)
- Note that `transform_frame_covariance_pose6x6()` can also be used to other …
> Frame conversions

- mavros/test/test_frame_conv.cpp
Full test run. Output positive:
```bash
Linking CXX shared library libgtest.so
[ 96%] Built target gtest
Scanning dependencies of target gtest_main
[ 96%] Building CXX object gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
Linking CXX shared library libgtest_main.so
[ 96%] Built target gtest_main
Scanning dependencies of target libmavros-frame-test
[100%] Building CXX object CMakeFiles/libmavros-frame-test.dir/test/test_frame_conv.cpp.o
Linking CXX executable /home/nuno/AIMAV_Project/devel/lib/mavros/libmavros-frame-test
[100%] Built target libmavros-frame-test
Scanning dependencies of target tests
[100%] Built target tests
Scanning dependencies of target _run_tests_mavros_gtest_libmavros-frame-test
-- run_tests.py: execute commands …
```
> unittests: corrected outputs from conversion tests

- mavros/include/mavros/mavros_uas.h
- mavros/src/lib/uas_frame_conversions.cpp
- mavros/test/test_frame_conv.cpp
* Updates to covariance calculation description
**Conclusion from inspection:** we need **Eigen** on code cause `std::transform` doesn't do matrix calculation, it is just multiplying each array element by each other and add it to the new array.
* added uinttest for Covariance conversion test; have to confirm the output but can't have a proper one without eigen.
> Unittests to covariance

- mavros/src/plugins/setpoint_attitude.cpp
The transformed quaternion wasn't being passed to set_attitude_target(), resulting in an incorrect attitude setpoint. I've now fixed this issue.
> Fixed bug in send_attitude_target()

- mavros_extras/src/plugins/distance_sensor.cpp
Basically the distance_sensor plugin could never initialize with the subscribers defined in the config.
> [distance_sensor] fix orientation empty error

- mavros_extras/src/gcs_image_bridge.cpp
- mavros_extras/src/plugins/image_pub.cpp
New stable release of opencv v3.0 includes some header changes. These changes, are retro-compatible with previous stable version 2.4, so they should be safe on both versions.
> opencv 3.0/2.4 header compatibility

- mavros/CMakeLists.txt
- mavros/mavros_plugins.xml
- mavros/src/plugins/manual_control.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/ManualControl.msg
Cleaned up pull request #377 (I messed up my repo in the process of fixing).
> Add MANUAL_CONTROL handling with new plugin

- mavros/CMakeLists.txt
Adding this dependency makes sure that mavros_msgs message headers are generated before the mavros library is built, since it needs those headers.
Otherwise you get intermittent build errors when building using multiple catkin_make threads, such as:
```
[  4%] Building CXX object third_party/mavros/mavros/CMakeFiles/mavros.dir/src/lib/uas_data.cpp.o
In file included from /home/odroid/ros/src/third_party/mavros/mavros/include/mavros/utils.h:21:0,
from /home/odroid/ros/src/third_party/mavros/mavros/src/lib/uas_data.cpp:18:
/home/odroid/ros/src/third_party/mavros/mavros_msgs/include/mavros_msgs/mavlink_convert.h:17:33: fatal error: mavros_msgs/Mavlink.h: No such file or directory
#include <mavros_msgs/Mavlink.h>
^
compilation terminated.
```
> Mavros library depends on mavros_msgs headers

- mavros/src/plugins/local_position.cpp
This adds a TwistStamped velocity topic to the output of the local_position node.  The velocity messages contains a vector3 of linear velocities in the ENU frame and a vector3 of the angular velocitires in the ENU frame.  Note that the angular velocity is expressed in the ENU frame for consistency though I would venture to guess people will quite possibly confuse this.  I'd be happy to change it to the body frame if people think that is best.  
The published topics of the plugin are now:
local_position/local/position(geometry_msgs/PoseStamped)
local_position/local/velocity(geometry_msgs/TwistStamped)
> Added velocity output of FCU's local position estimate to local_position plugin

- mavros/include/mavros/mavros_uas.h
- mavros/src/plugins/setpoint_raw.cpp
@vooon My integration tests found a bug in `setpoint_raw`. In `setpoint_position` the orientation (quaternion) is handled by the transform methods. But we don't have a Q in `setpoint_raw`, we just copy yaw/yaw_rate. It needs to be inverted. I only changed it for `local_cb` to test and to show you, do you have a suggestion how to fix this properly? I'm a little lost on the transformation templates ;)
> WIP: transform yaw and yaw rate from ENU to NED

- mavros/include/mavros/mavros_uas.h
- mavros/src/lib/uas_data.cpp
- mavros/src/plugins/local_position.cpp
Fixes #432
@scott-eddy : your latest change in the `local_position` plugin introduced a race condition that was previously handled by using "safe" methods to get the IMU data from `uas`.
@vooon: This PR adds another fallback method for velocity if that's your preferred solution. @scott-eddy it would probably be good if you give this a test.
> Use safe methods to get IMU data in local_position plugin

- mavros_extras/CMakeLists.txt
- mavros_extras/package.xml
- mavros_extras/src/copter_visualization.cpp
changes to mavros_extras/copter_visualization to make vehicle model configurable:
*  number of rotors
*  arm length
*  body width/height
(package now depends on TF for tf::createQuaternionMsgFromYaw but this could be removed)
> configurable vehicle model

- mavros/include/mavros/mavros_uas.h
- mavros/launch/px4_config.yaml
- mavros/src/lib/uas_frame_conversions.cpp
- mavros/src/plugins/altitude.cpp
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/imu_pub.cpp
- mavros/src/plugins/local_position.cpp
- mavros/src/plugins/setpoint_attitude.cpp
- mavros/src/plugins/setpoint_position.cpp
- mavros/src/plugins/setpoint_raw.cpp
- mavros/src/plugins/setpoint_velocity.cpp
- mavros/test/test_frame_conversions.cpp
- mavros_extras/src/plugins/mocap_pose_estimate.cpp
- mavros_extras/src/plugins/px4flow.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
- mavros_extras/src/plugins/vision_speed_estimate.cpp
This PR will add a nav_msgs/Odometry output to the local position plugin, solving #470 directly.  Additionally #438 will be addressed by this PR with an in-depth analysis of the current coordinate frames used, transformations between frames, and making these frames as [REP 105](http://www.ros.org/reps/rep-0105.html) and [REP 103](http://www.ros.org/reps/rep-0103.html) compliant with minimal impact on the current user base (e.g. with changing as few frame names as possible).
Coordinate Frame Examination
======
(https://github.com/mavlink/mavros/blob/master/mavros/src/lib/uas_frame_conversions.cpp)
Odometry Message Publication
======
Documentation
======
[Here](https://drive.google.com/open?id=1bDhaozrUu9F915T58WGzZeOM-McyU20dwxX-NRum1KA) is a discussion of the proposed changes and why they …
> WIP: Add odometry message to local position plugin & coordinate frame review

- mavros/src/lib/uas_stringify.cpp
We are creating a new flavor of the APM software stack in conjunction with the drone code community called APM:Sub. The code is currently being tracked at [bluerobotics/ardupilot](https://github.com/bluerobotics/ardupilot/tree/master/ArduSub). At the moment, this is the only change required to get mavros to work on our Pixhawk + APM:Sub stack. We'd be very thankful if you can pull this into the official mavros repo and include it in the next release.
Thanks!
CC @rjehangir
> Treat submarine vehicles like copter vehicles

- mavros_extras/src/plugins/px4flow.cpp
The entry 'quality' under the topic "px4flow/raw/optical_flow_rad" is always zero.The reason for this is in mavros/mavros_extras/src/plugins/px4flow.cpp the quality in the message is not forwarded to the topic. Please add one line
flow_rad_msg->quality = flow_rad.quality;
at around line 117. I tested it and this will fix it well.
> Fix px4flow quality

- mavros_extras/launch/f710_joy.yaml
- mavros_extras/scripts/mavteleop
update to `mavteleop` to allow support modes in -rc mode
* modes are read from the `~rc_modes` in yaml format eg. with `<rosparam>` (see examples below)
* tested with [Futaba flight controller](http://www.realflight.com/products/gpmz4520.html) and [Logitech gamepad](http://gaming.logitech.com/en-roeu/product/f710-wireless-gamepad)
* removed support for arm/disarm in RC mode as it is already available over RC with stick in lower-right position
> modified mavteleop to support RC modes

- mavros_extras/src/copter_visualization.cpp
track visualization in `copter_visualization` was constantly creating new markers (`marker.id` constantly incremented) which would eventually clog rviz and slow in down.
introduced `max_track_size` parameter to limit number of track markers, also used `CUBE_LIST` marker type instead of `CUBE` for efficiency as it allows rviz to batch rendering.
http://wiki.ros.org/rviz/DisplayTypes/Marker#Cube_List_.28CUBE_LIST.3D6.29
> Fix track visualization

- libmavconn/src/serial.cpp
The serial device was closed before calling io_service.stop() so io_service::run() never returned, leading to hang on join in MAVConnSerial::close()
Backtrace when mavros_node gets SIGINT:
```
#0  0x00007f80217e966b in pthread_join (threadid=140188059690752, thread_return=0x0) at pthread_join.c:92
#1  0x00007f80215602d7 in std::thread::join() ()
#2  0x00007f8020ccc674 in mavconn::MAVConnSerial::close() ()
#3  0x00007f8020ccc6f5 in mavconn::MAVConnSerial::~MAVConnSerial() ()
#4  0x00007f8020cc7b2e in boost::detail::sp_counted_impl_pd<mavconn::MAVConnSerial*, boost::detail::sp_ms_deleter<mavconn::MAVConnSerial> >::dispose() ()
#5  0x000000000040ee0a in boost::detail::sp_counted_base::release() [clone .part.27] [clone .constprop.472] ()
#6  0x000000000041eb22 in mavros::MavRos::~MavRos() () …
```
> MAVConnSerial: Stop io_service before closing serial device (Fixes #130)

- mavros/src/plugins/setpoint_raw.cpp
Fixes a bug where the ned_desired_orientation was not actually passed into set_attitude_target. Instead, the desired_orientation (wrong frame) was passed.
This addresses #536
> Fix bug #536 with orientation in setpoint_raw

- mavros/CMakeLists.txt
- mavros/mavros_plugins.xml
- mavros/src/plugins/hil_controls.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/HilControls.msg
Adding a plugin for publishing HIL_CONTROLS mavlink messages coming from the FCU as ROS messages in order to facilitate HIL simulation with MAVROS.
> Added a plugin that publishes HIL_CONTROLS as ROS messages

- mavros/src/plugins/hil_controls.cpp
This typo was fixed in the master branch, but not in the indigo-devel branch.
> Fixing a typo in HIL_CONTROLS plugin

- mavros/CMakeLists.txt
- mavros/mavros_plugins.xml
- mavros/src/plugins/hil_actuator_controls.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/HilActuatorControls.msg
- mavros_msgs/msg/HilControls.msg
This is the replacement message for the HIL_CONTROLS message.
I couldn't actually test if this compiles because I don't have ROS installed.
> add HIL_ACTUATOR_CONTROLS mavlink message

- README.md
A couple of typos fixed in the main README.md
it's -> its (where appropriate)
contain -> contains (ditto)
> README: fixed a couple of typos

- mavros/src/plugins/sys_status.cpp
- mavros_msgs/msg/State.msg
Used to know the state of APM based drone with Companion Computer.
> Plugins: add system_status to state message

- mavros/src/plugins/command.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
- mavros_msgs/srv/CommandTriggerControl.srv
1. Fixes a long-term bug in the vision plugin. Yaw between ENU and NED will now be rotated correctly. This was already done correctly in the `mocap` plugin (https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/mocap_pose_estimate.cpp#L117), but we were missing it in `vision_pose`.
2. Minor renaming in camera trigger interface to match PX4 naming conventions.
@vooon Please review and merge. These have been tested extensively both in PX4 SITL (with laser-scan odometry) and on hardware.
> Vision plugin fixes, Camera trigger fixes

- README.md
Add link to help mavros with ArduPilot users find help.
> README: add link to ArduPilot gitter chat

- mavros/src/plugins/safety_area.cpp
Added `SAFETY_ALLOWED_AREA` rx handler and publish `PolygonStamped` msg with the 2 points. Related to https://github.com/PX4/Firmware/issues/4167. To be sync with geofence function on the FW side, mainly to work with local position values.
> Added SAFETY_ALLOWED_AREA rx handler

- mavros/launch/apm_pluginlists.yaml
Ardupilot supports the SET_ATTITUDE_TARGET mavlink message so the setpoint-attitude should be removed from the blacklist.  This has been tested by a user.
> launch: remove setpoint-attitude from apm blacklist

- mavros_extras/src/plugins/odom.cpp
@jgoppert can you please test this and check if the current transforms work, using the mavros transform functions from `frame_tf.h`?
Still TODO:
> [WIP] Odometry Plugin review

- mavros/include/mavros/setpoint_mixin.h
- mavros/launch/apm_config.yaml
- mavros/launch/px4_config.yaml
- mavros/src/plugins/setpoint_accel.cpp
- mavros/src/plugins/setpoint_attitude.cpp
- mavros/src/plugins/setpoint_position.cpp
- mavros/src/plugins/setpoint_velocity.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/Float32Stamped.msg
- mavros_msgs/msg/Thrust.msg
> [WIP] Plugins: setpoint_attitude: add sync between thrust and attitude

- mavros/launch/px4_pluginlists.yaml
- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/rangefinder.cpp
This add ardupilot rangefinder message support. It will be deprecated with next version that support DISTANCE_SENSOR msg
> Extras: add ardupilot rangefinder plugin

- mavros_extras/src/plugins/distance_sensor.cpp
Currently if we send a distance message to FCU on ardupilot, the message is resend. This prevent heavy spamming.
> Extras: distance sensor don't spam when message are bounce back from FCU

- mavros_extras/src/plugins/distance_sensor.cpp
need new mavlink released for : https://github.com/mavlink/mavlink/commit/35a89a2af36f4c0a4024f7a7419b620626b0543f
> Distance sensors: uncrustify and and new sensor type

- mavros/launch/apm_config.yaml
- mavros/launch/px4_config.yaml
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/local_position.cpp
- mavros/src/plugins/sys_status.cpp
- mavros/src/plugins/waypoint.cpp
- mavros_extras/launch/px4flow_config.yaml
- mavros_extras/src/copter_visualization.cpp
- mavros_extras/src/plugins/fake_gps.cpp
- mavros_extras/src/plugins/px4flow.cpp
- mavros_extras/src/plugins/vibration.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
Solving default frame consistency in config files #789 
* Changing the `local_origin` frame to `map` for consistency.
* Correction of the `global_position/frame_id` and `local_position/frame_id` to map frame
> Solving default frame consistency in config files

- mavros/CMakeLists.txt
For arm & mips architecture, the linker must explicitly be asked to link the atomic library (with `-latomic`).
Otherwise, the linking fails with:
```
| devel/lib/libmavros.so: undefined reference to `__atomic_load_8'
| devel/lib/libmavros.so: undefined reference to `__atomic_store_8'
| collect2: error: ld returned 1 exit status
```
Linking `atomic` unconditionally as library is strictly needed only for arm & mips, but it seems not to imply any further differences with other architectures. Hence, this commit simply adds `atomic` unconditionally for a uniform handling of all machine architectures.
This is an alternative solution to the proposed solution in #790.
The issue was discovered cross-compiling mavros in meta-ros, the OpenEmbedded layer for ROS. Some further pointers are available …
> CMake: explicitly link the atomic library

- mavros/src/plugins/waypoint.cpp
- mavros_msgs/msg/WaypointList.msg
This PR makes the current waypoint sequence number more accessible.
Currently finding the sequence number requires iterating through `/mavros/mission/waypoints` and checking `is_current`.
This PR adds seq field to the waypointlist message outside of the waypoint array.
As discussed in https://github.com/mavlink/mavros/pull/798#issuecomment-327745029.
> waypoint: Publish current waypoint seq

- mavros/scripts/mavsys
- mavros/src/lib/enum_to_string.cpp
- mavros/src/lib/mavros.cpp
- mavros/src/plugins/sys_status.cpp
- mavros_msgs/srv/SetMode.srv
Also the enums are updated - can push this to another PR if needed.
> mavsys: mode: add solutions for setting AUTO.MISSION and AUTO.LOITER modes

- mavros/scripts/mavcmd
- mavros/scripts/mavparam
- mavros/scripts/mavsafety
- mavros/scripts/mavsetp
- mavros/scripts/mavwp
Some typos as I go:
commad -> command
safty -> safety
desiered -> desired
Start help messages with a capital letter.
Even though it seems trivial, I tested my commit with `catkin build` and `catkin run_tests` and everything succeeded.
> scripts: fix typos and improve help messages consistency

- mavros_extras/scripts/mavteleop
Items work with python3 and python2.7
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
> mavteleop: Move from iteritems to items for python3 support

- mavros/include/mavros/frame_tf.h
- mavros/src/lib/ftf_frame_conversions.cpp
- mavros/src/plugins/global_position.cpp
- mavros/test/test_frame_conversions.cpp
- mavros_extras/src/plugins/fake_gps.cpp
ENU<->ECEF transformations are totally screwed up resulting in crazy positions in global_position\local topic. fake_gps plugin is also affected.
P.S. This is my 1st contributing to mavros - tried to follow the conventions as much as possible.
> ENU<->ECEF transforms fix.

- mavros/src/plugins/global_position.cpp
global_position/local angular twist changed from NANs to zeroes to be able to show in RViz.
> global_position/local angular twist changed from NANs to zeroes.

- mavros/launch/apm_config.yaml
- mavros/launch/px4_config.yaml
- mavros/src/plugins/global_position.cpp
According to [ROS](http://docs.ros.org/jade/api/sensor_msgs/html/msg/NavSatFix.html), frame_id of NavSatFix message is 
> This is a Euclidean frame relative to the vehicle, not a reference  ellipsoid.
So, usually, this should be `base_link`, not `map`.
Some ROS packages (like [robot_localization](http://wiki.ros.org/robot_localization)) rely on it to be specified exactly this way. 
This pull request adds child_frame_id parameter for global_position plugin and uses it for 
- global_position/global/header/frame_id
- global_position/raw/fix/header/frame_id
- global_position/local/child_frame_id (to make it complete)
> GPS fix's frame_id changed to body-fixed.

- mavros_extras/src/plugins/fake_gps.cpp
I think it is better the earth variable is initialized at constructor.
> move member variable earth initialization

- mavros/src/lib/ftf_frame_conversions.cpp
- mavros/src/lib/ftf_quaternion_utils.cpp
PR out of https://github.com/mavlink/mavros/issues/892.
Considering the effort that would be needed to change the naming to `ypr` (and testing), I think we can leave it like this.
> mention rotation convention and fix NED to ENU description

- mavros/src/plugins/imu.cpp
The variables even say ENU but are actually converted to forward-left-up. I guess `mag_field` would have to be ENU as well?
> convert accel/gyro to enu not forward-left-up

- mavros/src/plugins/manual_control.cpp
PX4 supports "overriding" manual control inputs via MANUAL_CONTROL message: https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L1559 (did not check for APM).
I added `~manual_control/override` topic (not sure about the name, this is the analogy with `rc/override`), allowing user to control the copter with a "virtual" RC with normalised values. For example:
```
rostopic pub -r 5 /mavros/manual_control/override mavros_msgs/ManualControl "header:
seq: 0
stamp: {secs: 0, nsecs: 0}
frame_id: ''
x: 0.0
y: 0.0
z: 1000.0
r: 200.0
buttons: 0" 
```
in `POSCTL` mode makes the copter fly up and rotate (tested in SITL).
Also, I think `1` is the correct value for `queue_size` for such topics (`rc/override`, `manual_control/override`, etc), because we want to send …
> manual_control: add topic for sending MANUAL_CONTROL messages

- mavros/launch/apm_pluginlists.yaml
Ardupilot doesn't support hardware in the loop so this plugin is not needed.
Additionally, this prevents, but doesn't fix, the issue in #822
> Blacklist HIL for APM since it is not relevent

- libmavconn/src/tcp.cpp
- libmavconn/src/udp.cpp
In boost 1.66.0, which includes boost-asio 1.12.0, the asio interfaces have been changed to follow the "C++ Extensions for Networking" Technical Specification [1]. As a consequence, resolvers now produce ranges rather than iterators.
This commits retains the original behaviour selecting the begin iterator from the provided range when using boost >= 1.66.0.
A preprocessing directive ensures backwards compatibility using the provided boost-asio version [2].
The issue was identified in a build with the cross-compilation tool chain provided in the meta-ros OpenEmbedded layer [3].
[1] http://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/net_ts.html
[2] https://github.com/boostorg/asio/commit/0c9cbdfbf217146c096265b5eb56089e8cebe608
[3] http://github.com/bmwcarit/meta-ros
> compile also with boost >= 1.66.0

- mavros/launch/apm.launch
- mavros/launch/node.launch
- mavros/launch/px4.launch
I can see cases were we don't want our system to kill all the nodes if the mavros node dies. Instead, allow the user to specify a new `respawn_mavros` argument if they want the mavros node to respawn rather than kill the whole roslaunch.
The argument name was chosen based on gazebo's launch file (see [empty_world.launch](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/9cbc4bfd9b0caf763387cb203f6bf695071cae07/gazebo_ros/launch/empty_world.launch#L17)), so this should feel familiar to users.
> launch: add optional respawn_mavros arg

- mavros/src/plugins/sys_status.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/StatusText.msg
This adds the ability to listen to and send STATUSTEXT messages to the FCU. Sent STATUSTEXT can then be received by QGroundControl (and read out if the severity is high enough) automatically over telemetry as if they were sent by the FCU.
To make use of this, one needs to enable mavlink forwarding on the FCU. On PX4, that can be achieved with the `-f` command when running `mavlink start`.
> Add ability to send STATUSTEXT messages

- libmavconn/include/mavconn/serial.h
- libmavconn/src/serial.cpp
Some common USB-UART converters like the FTDI accumulate individual bytes from the serial link in order to send them in a single USB packet ("Nagling" - https://en.wikipedia.org/wiki/Nagle%27s_algorithm). This commit sets the ASYNC_LOW_LATENCY flag, which the FTDI kernel driver interprets as a request to drop the Nagling timer to 1ms (i.e send all accumulated bytes after 1ms.)
This reduces average link RTT to under 5ms at 921600 baud (it is 20-30 ms on master), and enables the use of mavros in systems where low latency is required to get good performance for e.g estimation and controls. As a side effect, this also greatly increases performance of timesync on serial links and prevents the hard-resets we've been seeing.
> libmavconn : enable low-latency mode on Linux

- mavros/src/plugins/ftp.cpp
Fixes typo in the error message.
> FTP plugin: fix typo in the error message

- mavros/launch/apm_pluginlists.yaml
it is now support in Master starting from https://github.com/ArduPilot/ardupilot/commit/12fd19ea265babe6be716e7159d91d8f95be3512
> launch : remove vision_pose_estimate from blacklist on ardupilot

- mavros/include/mavros/frame_tf.h
- mavros_extras/src/plugins/odom.cpp
- mavros_extras/src/plugins/vision_pose_estimate.cpp
Updates `vision_pose_estimate` plugin so it can send the covariance matrix also. Follows the Mavlink spec update in https://github.com/mavlink/mavlink/pull/724. Requires a `mavlunk-gbp-release` update.
Also, generalizes `covariance9d_urt_to_mavlink` to `covariance_urt_to_mavlink` so to be able to parse URT values for matrices of other sizes.
> extras: add covariance parsing to VISION_POSITION_ESTIMATE

- mavros_msgs/msg/CommandCode.msg
I used cog to get all the available commands from `MAV_CMD` enum, excluding:
1. An exclusion list that includes 'SPATIAL', 'USER', 'WAYPOINT' user defined commands;
2. Deprecated commands (by description inspection).
This way, updating the command codes to be used by services.
> CommandCode: update list of available commands on MAV_CMD enum

- mavros/src/plugins/imu.cpp
Sorry - converted units wrong on the differential and static pressure in #1001
PX4 also using new uorb for the static pressure which is in pa now (used to be millibar) https://github.com/PX4/Firmware/blob/master/msg/vehicle_air_data.msg#L4
> imu plugin: fix pressure units

- mavros/src/plugins/setpoint_attitude.cpp
Discussed with @TSC21 
Topic list:
```
/mavros/setpoint_accel/accel
/mavros/setpoint_attitude/target_attitude
/mavros/setpoint_attitude/thrust
/mavros/setpoint_position/global
/mavros/setpoint_position/local
/mavros/setpoint_raw/attitude
/mavros/setpoint_raw/global
/mavros/setpoint_raw/local
/mavros/setpoint_raw/target_attitude
/mavros/setpoint_raw/target_global
/mavros/setpoint_raw/target_local
/mavros/setpoint_velocity/cmd_vel
/mavros/setpoint_velocity/cmd_vel_unstamped
```
Basically, while going over the documentation it seemed fitting to change the topic name back to `attitude` as documentation states and because the `target_*` topics used by setpoint_raw are loopback publishers.
I doubt the topic is currently widely used as the parameter to enable it wasn't documented till today,
> setpoint_attitude: rename topic from target_attitude to attitude

- mavros/launch/px4_config.yaml
- mavros/src/lib/enum_to_string.cpp
- mavros_extras/src/plugins/odom.cpp
This updates the `odom` plugin to send [`ODOMETRY`](http://mavlink.org/messages/common#ODOMETRY) Mavlink msgs instead of [`LOCAL_POSITION_NED_COV`](http://mavlink.org/messages/common#LOCAL_POSITION_NED_COV) + [`ATT_COV`](http://mavlink.org/messages/common#ATTITUDE_QUATERNION_COV), which required an higher bandwidth given the size of `LOCAL_POSITION_NED_COV`. Also, this merges the odometry data into the same message, removing the need for posteriors sync of the pose and velocity data, which would get to the FCU at different time frames.
This will be followed by the respective support for the PX4 Pro firmware.
> Extras: update odom plugin to send Mavlink ODOMETRY msgs

- mavros/include/mavros/frame_tf.h
- mavros/src/plugins/setpoint_attitude.cpp
- mavros/src/plugins/setpoint_raw.cpp
This is an attempt to fix https://github.com/mavlink/mavros/issues/751. @ChrisGermany can you give a try on this branch and check if this solves your problem (for both yaw and yaw rate setpoints)?
Just `git clone https://github.com/TSC21/mavros.git -b setpoint_yaw_fix` and test.
> setpoint_raw: correct yaw transform; remove yaw transform methods

- mavros_extras/src/plugins/odom.cpp
The msgs spec states that the position and orientation should be on the local frame, while the twist data should be on the body frame.
**UPDATE:** this is not actually right -> it depends on the frames where the data is sent on. *example:* If a VIO app sends the velocity of a vehicle (the `child_frame_id` that navigates in an `odom` `frame_id`), then the velocity of the vehicle needs to be parsed on the the same frame of the `child_frame_id`, which means the vehicle body frame. The orientation should though be rotated from the FLU to the FRD orientation.
> [WIP] extras: odom: adapt the transform according to the frames

- mavros/CMakeLists.txt
- mavros/mavros_plugins.xml
- mavros/src/plugins/vfr_hud.cpp
- mavros/src/plugins/wind_estimation.cpp
Makes a new wind estimation plugin handling both APM and PX4 specific wind messages.
- moves old APM wind publisher from vfr_hud to the new wind plugin
- the PX4 message contains a *summed* horizontal wind speed convariance (i.e. x cov + y cov). This value is placed in the first covariance array slot for now, and the vertical in the 3rd.
resolves #1008
> add wind estimation plugin

- mavros/launch/apm_config.yaml
- mavros/launch/px4_config.yaml
- mavros/src/plugins/global_position.cpp
GPS accuracy published by mavros is now based on accuracies reported by FCU in `GPS_RAW_INT` message if using mavlink v2.0. Otherwise they are approximated by HDOP & VDOP values, scaled by GPS User Equivalent Range Error (UERE) measured in meters.
According to #1020.
> GPS accuracy wo approximations

- libmavconn/README.md
- libmavconn/include/mavconn/udp.h
- libmavconn/src/interface.cpp
- libmavconn/src/udp.cpp
- mavros/README.md
For now, the GCS bridge has a «UDP broadcast» mode, but this name is quite confusing, because it’s not real broadcasting. In fact, it’s just an automatic GCS discovery. 
But, for some environments, simple UDP broadcasting is preferable. For example:
1. It allows viewing and controlling the vehicle from multiple GCS simultaneously (tested)
2. Sometimes, it better fits multiple vehicles communications purposes (e. g. drone - charging station - GCS, drones swarms, etc)
3. It can be faster over Wi-Fi connections, because broadcasting doesn’t have Wi-Fi level acks (unlike of unicasting).
The protocol name (udp-bb) is quite random, can be discussed.
> Add permanent UDP broadcasting for GCS bridge

- mavros/src/plugins/sys_time.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/TimesyncStatus.msg
Mavros version of https://github.com/PX4/Firmware/pull/9365.
Tested in SITL. Pending test on vehicle, but everything should be working correctly already.
> Advanced Time Synchronisation

- mavros/include/mavros/mavros.h
- mavros/src/lib/mavros.cpp
When using GCS bridge with UDP (or UDP broadcast) mode on Wi-Fi, even when QGC is off, it's a lot of traffic (MAVLink messages) making other Wi-Fi connections slow.
This PR adds a parameter `gcs_quiet_mode`, turning more intelligent mode: the bridge retransmits only `HEARTBEAT` messages before any other device (GCS) sends any message. After that, all telemetry is switched on. If the GCS is not sending anything for 20 seconds, telemetry is switched off again.
This has been tested with QGC and a PixHawk drone, and it works quite well.
> GCS bridge: pass only HEARTBEATs when GCS is offline

- mavros/src/plugins/setpoint_velocity.cpp
Similar to what is done with the linear velocity, this patch allows to apply the proper rotation to the yaw rate according to the frame of reference. *note:* PX4 only processes the yaw rate wrt to the local frame. This is already done properly in `setpoint_raw` plugin.
> setpoint_velocity: fix yaw rate setpoint rotation

- mavros_extras/src/plugins/gps_rtk.cpp
The namespace is wrong and has to be corrected to be loadable.
> gps_rtk: Fix wrong namespace (std->extras)

- libmavconn/CMakeLists.txt
- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/log_transfer.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/LogData.msg
- mavros_msgs/msg/LogEntry.msg
- mavros_msgs/srv/LogRequestData.srv
- mavros_msgs/srv/LogRequestEnd.srv
- mavros_msgs/srv/LogRequestList.srv
This adds basic support for messages, that allow to implement efficient log transfer even for very large log files. These messages are used by QGroundControl to download log files, but there are times, when using QGC to download logs is inappropriate. For example, when one is conducting automated testing of UAVs (without human intervention).
The endpoints (services, topics) are called `raw/...`, because I intend to add "high-level" functionality, that will add convenient abstraction over this functionality. That abstraction, however, needs not be a part of this request.
> Add support for log transfer related messages

- mavros_extras/src/plugins/odom.cpp
Was testing the odom message being pulled into PX4, noticed my covariances weren't being passed through (they were just empty zero matrix instead). 
I'm assuming it's better to actually use the covars or is there a reason to override it to zeros?
> Fix odom message to use covariance from msg

- mavros/launch/apm_pluginlists.yaml
This resolves [this issue](https://github.com/mavlink/mavros/issues/1080) by enabling the mocap_pose_estimate plugin.
The mocap_pose_estimate has been tested ([video](https://www.youtube.com/watch?v=P3qllsrt-_M), [blog](https://discuss.ardupilot.org/t/indoor-flight-with-external-navigation-data/29980)) and shown to work well.
> launch: remove mocap_pose_estimate from apm blacklist

- libmavconn/src/udp.cpp
> udp: bind should be called after reuse_address is set

- mavros/src/mavros/command.py
- mavros/src/plugins/command.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/srv/CommandTriggerControl.srv
- mavros_msgs/srv/CommandTriggerInterval.srv
Adapt trigger_control service to current mavlink cmd spec. Add a new service to change trigger interval and integration time.
Fixes #987
@mhkabir
> Fix of trigger setup and control via mavlink cmd interface 

- mavros/src/plugins/hil.cpp
The issue and the solution I have reported here#1110 .
Here is the flexible way to avoid the eigen not perfectly aligned issue on 32 bits system.If you libeigen support SSE packet, you will need this fix on your board.
[http://eigen.tuxfamily.org/dox-devel/group__TopicStructHavingEigenMembers.html](url)here explain why this fix is needed, and why it can also fit X86-X64system.
In addition,the version is pasted here :ROS distro is above Lunar ,and GCC is above 5.4 and libeigen3 is above 3.3.4-4
> with this fix ,it will avoid eigen error on 32 bits system

- libmavconn/include/mavconn/interface.h
- libmavconn/include/mavconn/msgbuffer.h
- libmavconn/include/mavconn/serial.h
- libmavconn/include/mavconn/tcp.h
- libmavconn/include/mavconn/udp.h
- libmavconn/src/interface.cpp
- libmavconn/src/serial.cpp
- libmavconn/src/tcp.cpp
- libmavconn/src/udp.cpp
This PR adds the possibility to override the source component ID through the `send_message()` and `send_message_ignore_drop()` methods. This allows one to set the specific component ID for each message being sent, which is useful for use cases as https://github.com/mavlink/mavros/pull/1118, where one wants to check the status of certain processes on a companion computer.
@baumanta @thomasgubler this should address what you are looking for. The way you can set this is by adding the respective ID to https://github.com/mavlink/mavros/pull/1118/files#diff-8aa5199f38db01aa1a7258093d338c99R78,
```c++
UAS_FCU(m_uas)->send_message_ignore_drop(heartbeat, proc_id);
```
where the `proc_id` matches the ID you set for a certain process running on the companion computer. Note that this ID should be …
> libmavconn: add the possibility to override the source component ID

- mavros/src/mavros/param.py
Small fixes to param.py to allow mavros to be called from python2 and python3 scripts
> Fix mavros/param.py to work in python2 and python3, #940

- mavros/src/plugins/rc_io.cpp
Mavlink 2 extension to [`SERVO_OUTPUT_RAW`](https://mavlink.io/en/messages/common.html#SERVO_OUTPUT_RAW) allows publishing the output of 16 servos. This PR addresses it and extends that support to `rc_io` plugin.
> rc_io: extend handle_servo_output_raw to 16 channels

- mavros/include/mavros/frame_tf.h
- mavros/launch/px4_config.yaml
- mavros/src/lib/uas_data.cpp
- mavros_extras/src/plugins/odom.cpp
This pull request is part of the effort to have a full odometry pipeline that allows sending and receiving odometry data. This implements the [`ODOMETRY`](https://mavlink.io/en/messages/common.html#ODOMETRY) handler in the `odom` plugin.
So to keep the consistency regarding the usage of `tf2` and tf lookups to apply the transforms, the `local_origin_ned`<->`fcu_frd` is published, in order to allow the following tf tree.
Soon enough the above transform implementation should be brought to the frame transform API and replace the static Eigen math being applied.
Here's a [demo video](https://drive.google.com/open?id=1gUFYf4k2TBTApRXXH6QAzUDJwk-QHvQX), which allows to see the Odometry data in both Rviz, `rostopic echo` and also with the comparison with QGC Mavlink Inspector.
> odom: add ODOMETRY handler and ROS publisher

- mavros_msgs/msg/LogData.msg
.. so that it matches the mavlink type, that is used for this message. Otherwise, the value for this field wraps around at 0xffffffff and confusion ensues.
> mavros_msgs/msg/LogData.msg: Define "offset" field to be of type uint32

- mavros/src/plugins/sys_status.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/VehicleInfo.msg
- mavros_msgs/srv/VehicleInfoGet.srv
Service allow to request : 
- my target vehicle
- a specific sysid/compid
- all vehicles seen by mavros
Took all comment from https://github.com/mavlink/mavros/pull/1147 and made a much more elegant solution. 
I used an unordered_map with key & mavros_msgs::VehicleInfo directly rather than defining a new class/struc VehicleInfo and a to_msg() function like in the waypoint plugin.
Thanks !
> VehicleInfo : add srv into sys_status plugin to request vehicule basic info

- mavros/scripts/mavsys
- mavros/src/plugins/sys_status.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/srv/MessageInterval.srv
This PR attempts to close this issue: https://github.com/mavlink/mavros/issues/370
- new set_message_interval service added which accepts MessageInterval requests which provide a desired message id and rate (in hz) and then sends a COMMAND_LONG (using the CommandLong service) containing a MAV_CMD_SET_MESSAGE_INTERVAL.
- The only slight complexity is that the request specifies a rate while the mavlink message provides an interval in us (I figured a rate was easier to use but it's possible this logic should have been put in mavsys instead of within the service).
- If the rate is set to 0 or -1 set the outgoing message-interval is also set to 0 or -1 which sets the rate to the default or turns off the message.  Perhaps it would be more logical to have the caller specify "rate=0" to turning …
> Add support for set message interval

- mavros/launch/apm_config.yaml
- mavros/launch/apm_pluginlists.yaml
- mavros/launch/px4_config.yaml
- mavros/launch/px4_pluginlists.yaml
- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/wheel_odometry.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/Float32ArrayStamped.msg
- mavros_msgs/msg/WheelOdomStamped.msg
This PR aims to make possible computing of wheel odometry on a companion computer with encoders connected to autopilot.
Supersedes PR #863.
Connected PRs:
[mavlink/mavlink #799](https://github.com/mavlink/mavlink/pull/799),
[ArduPilot/mavlink #55](https://github.com/ArduPilot/mavlink/pull/55),
[ArduPilot/ardupilot #7252](https://github.com/ArduPilot/ardupilot/pull/7252)
> Wheel odometry plugin added

- mavros/launch/px4_config.yaml
This should be set to unitary by default, as being 0 means there's no thrust.
@lamping7 FYI.
@vooon what's the possibility of having a 0.28.1 minor release to bring this? The reason is that this is currently breaking PX4 CI.
> px4_config: set the thrust_scaling to one by default

- mavros_extras/CMakeLists.txt
- mavros_extras/package.xml
As stated in #1166 mavros_extras does not build with 
`catkin build`
because odom.cpp includes tf2_eigen headers, but tf2_eigen is not listed as dependency. This PR fixes the issue.
> added tf2_eigen to dependencies

- mavros_extras/src/plugins/obstacle_distance.cpp
This PR attempts to resolve issue https://github.com/mavlink/mavros/issues/1082.  The issue is that the obstacle_distance plugin does not correctly handle LaserScan messages from sensors with more than 72 distances.  The limitation comes from the [OBSTACLE_DISTANCE mavlink message](https://mavlink.io/en/messages/common.html#OBSTACLE_DISTANCE) which can only carry up to 72 distances.
The existing code simply truncates the data while the new code instead "compresses" the data to fit.  It does this by combining adjacent distances (always choosing the shortest distance).
So as to ensure as little impact as possible on existing users of this plugin, the new "compression" code is separated out with an if/else.
I've tested this on an Nvidia Tx2 running ROS/mavros with an RPLidarA2.  I modified …
> obstacle_distance: combine sensor distances to fit within distances array

- mavros/launch/apm_config.yaml
Setting thrust_scaling in the setpoint_raw message (in my case, to use /mavros/setpoint_raw/attitude)
Without it, when using Gazebo, get the following problem
"Recieved thrust, but ignore_thrust is true: the most likely cause of this is a failure to specify the thrust_scaling parameters on px4/apm_config.yaml. Actuation will be ignored." from the function void attitude_cb in setpoint_raw.cpp (http://docs.ros.org/kinetic/api/mavros/html/setpoint__raw_8cpp_source.html)
> Update apm_config.yaml - Adding thrust_scaling to 1.0 in setpoint_raw msg

- mavros_extras/src/plugins/odom.cpp
This matches the new field naming for the `ODOMETRY` message: https://github.com/mavlink/mavlink/pull/917/files#diff-ceacc1e2390186650146a45be8fcb691R4970.
This requires a new release of `mavlink-gbp-release` @vooon.
> extras: odom: update velocity covariance fields from 'twist' to 'velocity_covariance'

- mavros_extras/src/plugins/gps_rtk.cpp
Adding fragment_id in both the for loop an in the variable redundant and duplicated
> gps_rtk: fix multi segment messages

- mavros/launch/apm_config.yaml
Possible regression from: https://github.com/mavlink/mavros/commit/762895ccc01a3ae3b2de9a3f4dfc894afdd65668
This space causes an error when running `roslaunch`:
```
error loading <rosparam> tag:
file /opt/ros/kinetic/share/mavros/launch/apm_config.yaml contains invalid YAML:
while parsing a block mapping
in "<string>", line 4, column 1:
startup_px4_usb_quirk: false
^
expected <block end>, but found '<block mapping start>'
in "<string>", line 103, column 2:
setpoint_raw:
^
XML is <rosparam command="load" file="$(arg config_yaml)"/>
The traceback for the exception was written to the log file
```
> remove leading space before setpoint_raw in apm_config.yaml

- mavros/src/plugins/command.cpp
It's confusing now, when you receive an answer: 4 (`MAV_RESULT_FAILED`) on command long, because after you dig into command processing side, in my case it's px4 firmware, you'll see that there is no possible answer `MAV_RESULT_FAILED` on the command.
This changes make it more explicit.
Thanks!
> mavros/src/plugins/command.cpp: log if command's wait ack timeout

- mavros/src/plugins/sys_status.cpp
This addresses #1107 and #1227, by filtering incoming heartbeats
by component ids before publishing the state.
> Filter heartbeats by component id

- mavros_extras/src/plugins/obstacle_distance.cpp
Fixed an issue when the laser scan topic contains NaN values they where being sent as 0 distances.
> Obstacle_distance plugin: NaN values reported as 0 distance

- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/mount_control.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/MountControl.msg
I have been trying to control the gimbal continously while the vehicle is constantly being commanded with continuous setpoints in offboard mode. This can be used for image based object / human tracking control. 
I have been trying to use `actuator_setpoints` with mixer group = 2 but this led to some [problems](https://discuss.px4.io/t/on-realtime-control-of-gimbal-from-companion-computer/11468). However, to use actuator control setpoints, `vmount` needs to be disabled.
A better alternative is to use `MAV_CMD_DO_MOUNT_CONTROL` message as this utilizes the `vmount` running on the drone. However, the `command` plugin in mavros only has a service interface, which is not suited for controlling the gimbal continuously.
**Solution**
This PR adds a MountControl plugin, which streams a …
> Add Mount Control plugin to control mount continuously

- mavros/src/plugins/global_position.cpp
This check makes sure the gp_origin is not incorrectly set when mavros is launch before aircraft has completed its boot up and obtained a gps fix.  The issue is described in this issue here https://github.com/mavlink/mavros/issues/1213
> fix for global_position/local sometimes having incorrect position

- mavros/src/lib/uas_data.cpp
There's a tf tree loop that's cased by broadcasting two static transforms between the same frames. Most ROS code ignores this but some nodes get very upset when they see a loop.
> Fix tf loop

- mavros/src/plugins/global_position.cpp
A Lat/Lon/Alt(AMSL) was being converted to ECEF by a function expecting Lat/Lon/Alt(HAE), so I changed the altitude to HAE prior to converting.
I took some data of the vehicle gps position (lat/lon/alt above ellipsoid) and the global origin (ecef) both before and after the change. During data collection, the PX4 simulation had just started and the vehicle had not moved/flown from starting point.
```
$ rostopic echo -n 1 -b gp_origin_before_2019-08-16-14-19-07.bag /mavros/global_position/raw/fix
header:
seq: 1829
stamp:
secs: 1565979547
nsecs: 336346368
frame_id: "pose_estimation"
status:
status: 0
service: 1
latitude: 52.0911111
longitude: 5.1202772
altitude: 43.4971884361
position_covariance: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
position_covariance_type: 2
---
$ rostopic echo -n …
```
> Fix global origin conversion to ecef

- mavros_extras/src/plugins/obstacle_distance.cpp
The plugin left room to put in data which was too big for uint16_t, which would result in wrapped data.  Now each value is checked and replaced with UINT16_MAX if it was too big, also NANs are handled properly.
> fix corner case in obstacle distance plugin

- mavros/src/plugins/imu.cpp
Depending on order of messages from the FCU, it was possible for the `imu/data` topic messages to contain uninitialised linear acceleration values. Added initialisation of the `linear_accel` values.
Also added a check that accelerometer data has been received. If this is not the case, element 0 of the covariance matrix is set to -1 as per the [`sensor_msgs/Imu`](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Imu.html) definition.
> Fix uninitialized IMU data

- mavros/src/plugins/setpoint_position.cpp
Previously global position setpoints were converted into local position setpoints in the setpoint position plugin. This was a workaround since flight controllers were not supporting the mavlink message `SET_POSITION_TARGET_GLOBAL_INT`.
Following https://github.com/PX4/Firmware/pull/12819, I think it makes sense to have the proper implementation of passing the [`SET_POSITION_TARGET_GLOBAL_INT`](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_GLOBAL_INT) for setpoints. I did not get rid of the previous workaround on converting the global position setpoints to local position setpoints, but moved it to subscribe to the topic `~global_to_local` to make it more explicit that it is doing the conversions on the companion side. 
Still there are a few things that needs to be …
> Use SET_POSITION_TARGET_GLBOAL_INT for global position setpoints

- mavros/src/plugins/sys_status.cpp
- mavros_msgs/msg/State.msg
We need to know whether the drone is in a manual state or not. In the HEARTBEAT mavlink message there is a flag for that. The alternative would be to see if /mavros/state/mode is any of the manual modes, but this PR would be more compliant with mavlink.
> added manual flag to mavros/state

- mavros/src/plugins/command.cpp
Sometimes commands take more time than default 5 seconds. Due to a low bandwidth of UART and a high rate of some mavlink streams. To eliminate this problem it's better to provide the parameter to configure the command's ack timeout.
I've not found any place in the code. where I can fix documentation for this changes.
> plugin Command: add parameter `command_ack_timeout`

- mavros_extras/src/plugins/mount_control.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/srv/MountConfigure.srv
This PR is a follow up of #1257 where it adds a service to configure the `MOUNT_MODE` for the `mount_control` plugin
> Add mount mode with MAV_CMD_DO_MOUNT_CONFIGURE

- mavros/src/plugins/command.cpp
Due to a recent commit, I got the following erros:
```
[ERROR] [1569574307.019612897]: Plugin command load exception: Failed to load library /home/dummy/sitebots-controller/devel/lib//libmavros_plugins.so. Make sure that you are calling the PLU
GINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/dummy/sitebots-con
troller/devel/lib//libmavros_plugins.so: undefined symbol: _ZN6mavros11std_plugins13CommandPlugin19ACK_TIMEOUT_DEFAULTE)
```
Moving the static constexpr ACK_TIMEOUT_DEFAULT out of the class resolved that issue for me. This is consistent with the double constants in ./mavros/src/plugins/imu.cpp and ./mavros/src/plugins/hil.cpp.
> moving ACK_TIMEOUT_DEFAULT out of class

- libmavconn/include/mavconn/interface.h
- libmavconn/src/interface.cpp
Currently the dropped_packets & parse_error counters are always published as 0 in mavros_diag.cpp.
This seems to be caused by using the wrong status struct.
Seems like mavros was editing m_status after mavlink_frame_char_buffer. This struct
seems to be the parsing state, and looks like it shouldn't be modified by the caller (for example
status->parse_error is zeroed out in the end of mavlink_frame_char_buffer).
Also, the crc & signature checks done in mavros seems redundant.
r_mavlink_status seems to be the struct that holds the mavlink connection information, therefore I
changed get_status to return it instead.
This fixes #1285.
> libmavconn: simplify parse_buffer, and fix dropped_packets and parse_error counters

- mavros/include/mavros/mavros_uas.h
- mavros/launch/px4_config.yaml
- mavros/src/lib/uas_data.cpp
- mavros_extras/src/plugins/odom.cpp
With this PR a proper tf tree is built and the odometry plugin simplified. This should simplify providing the FCU with external position/odometry information.
Fixes #1293
The suggested changes include:
- odom plugin is not publishing tfs anymore.
- multiple static tfs are published in uas_data.cpp. (includes a fix proposed by @mhkabir )
- transform between local frame and body frame is published by local_position. 
(needed to change the frame_id in px4_config.yaml)
- change default frame_id in px4_config.yaml for all plugin.  (to be discussed)
- simplify the odom plugin to support less frame options.
- fixed inconsistent usage and naming of transformations.
UPDATED: tf tree (including frames that are published by Realsense T265 VIO sensor):
The send odometry messages, both to and from …
> TF tree and odometry plugin

- mavros/src/plugins/command.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/srv/CommandVtolTransition.srv
Recent [support](https://github.com/PX4/Firmware/pull/12532) for offboard mode on fixedwing has enabled VTOLs to be controlled fully in offboard mode in both fixed wing and multirotor modes.
This PR enables being able to command a transition using the `MAV_CMD_DO_VTOL_TRANSITION` mavlink message to trigger a transition using a rosservice.
The video and log below shows a single position setpoint is sent to the vehicle as [0, 0, 10.0], and a transition is triggered in between. The setpoint is passed on as a L1 reference, therefore the vehicle circles around the setpoint when in fixed wing mode.
Video: https://youtu.be/NZy6nbt0cnk
Log: https://review.px4.io/plot_app?log=fbf73fe6-ee15-437a-a0cb-3d3da0037222
> Add vtol plugin for vtol transitions

- mavros_extras/src/plugins/obstacle_distance.cpp
Makes it possible to specify the 'frame' field in the MAVLink
OBSTACLE_DISTANCE message sent by this plugin. Previously the
frame was not defined, which means it defaulted to MAV_FRAME_GLOBAL.
(See https://mavlink.io/en/messages/common.html#OBSTACLE_DISTANCE)
The default frame is therefore still MAV_FRAME_GLOBAL.
Fix #1330.
Seems to work fine, for instance when I set frame `BODY_FRD` and check the corresponding message in the px4 simulator, I get `frame: 12` which matches (https://mavlink.io/en/messages/common.html#MAV_FRAME).
> obstacle distance plugin: Add ROS param for mavlink frame

- mavros_extras/src/plugins/landing_target.cpp
I think these four conditionals are buggy:
The first is    (x and y) > 0
and should be   (x > 0) and (y > 0)
(This one actually works the way it's written.)
The second is   (x < 0 and y) > 0
and should be   (x < 0) and (y > 0)
The third is    (x and y) < 0
and should be   (x < 0) and (y < 0)
The fourth is   (x < 0 and y) < 0
and should be   (x > 0) and (y < 0)
> landing_target: Fix cartesian to displacement bug

- mavros/CMakeLists.txt
- mavros/mavros_plugins.xml
- mavros/src/plugins/setpoint_trajectory.cpp
As MAVs are dynamically constrained, the capability to track trajectories are important for high performance maneuvers. As the flight controller do not provide trajectory tracking capabilities, current implementation of trajectory planners usually send setpoints to the flight controller in order of time. This trivial task has been implemented on the planner side outside of mavros.
This PR adds a plugin to mavros for setting a trajectory as a setpoint using the [MultiDOFJointTrajectory](http://docs.ros.org/melodic/api/trajectory_msgs/html/msg/MultiDOFJointTrajectory.html) message.
The plugin receives a trajectory, and sends the reference with the [SET_POSITION_TARGET_LOCAL_NED](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_LOCAL_NED) message to the flight controller by …
> Setpoint trajectory plugin using MultiDOFJointTrajectory message

- mavros_extras/package.xml
This Fixes #1344 where it adds a new dependency for `trajectory_msgs` that was introduced by #1301
> Add trajectory_msgs as dependency

- libmavconn/src/tcp.cpp
This PR addresses #1350 
To make sure libmavconn compiles with both boost versions >= 1.70 and below 1.70 a macro is created to ensure the correct API call is made for get_io_service().
> add macro for get_io_service() to work with boost>1.70

- mavros_extras/src/plugins/obstacle_distance.cpp
The computation `req->angle_increment * RAD_TO_DEG` correctly computes
angle increment in degrees as a float, but the `increment` field of the
OBSTACLE_DISTANCE MAVLink message is a uint8, so the float value gets
truncated. So if your real increment is 10 degrees, you may have a floating
point value of something like 9.9999997, which results in the integer value
9 getting written to the increment field.
An improvement would be to round properly, with something like
`static_cast<uint8_t>(increment_deg_float)`,
but a better solution is to allow non-integer degree values for the
increment, which is supported by the `increment_f` field. According
to the MAVLink reference, increment_f is used instead of increment
whenever increment_f is nonzero.
---
NOTE: `increment_f` is a Mavlink 2 …
> obstacle_distance: Fix wrong angle increment

- mavros_extras/src/plugins/odom.cpp
I was fighting a delay pushing odom over sik radios because I wanted to get mocap working without an onboard computer for a particular application. I fixed this by setting the subscription queue to 1 and I think this is probably a good idea in general.
> Change odometry subscription queue to 1 to avoid buffering.

- mavros/CMakeLists.txt
This allows build to complete successfully. The `trajectory_msgs` package is a requirement and is specified in the package.xml, but not in CMakeLists.txt.
> Include trajectory_msgs in CMakeLists.txt

- mavros/scripts/mavsafety
For the circumstances to use emergency-stop feature without RC or ground control station. It is used as same as arm, disarm;
`mavsafety kill`
> mavsafety kill feature for emergency stop

- mavros_extras/src/visualization.cpp
In the current implementation, it is completely unclear where the "nose" of the device is directed.
In order not to overload the scene with elements, I propose adding a parameter that will tint the front and rear propellers in different colors, red and white, respectively. This logic used on DJI propellers on the f450 and f500 frame.
> Visualization of the direction of the device

- mavros/src/plugins/command.cpp
- mavros_msgs/srv/CommandHome.srv
Adding yaw to CMD_DO_SET_HOME. Implementation in PX4 is already done (https://github.com/PX4/Firmware/pull/14810).
> add yaw to CMD_DO_SET_HOME

- mavros/src/plugins/wind_estimation.cpp
This PR fixes the 180 degree rotation of the wind direction in the ArduPilot wind message handler. I also further tested this code in the ArduPilot SITL simulator, so I removed the TODO comment.
> wind plugin: fix ArduPilot wind transformation

- mavros_extras/CMakeLists.txt
- mavros_extras/README.md
- mavros_extras/mavros_plugins.xml
- mavros_extras/package.xml
- mavros_extras/src/plugins/gps_status.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/GPSRAW.msg
- mavros_msgs/msg/GPSRTK.msg
The timestamps for the gps_status topics take into account the mavlink time and uses the convienence function
> Add gps_status plugin to publish GPS_RAW and GPS_RTK messages from FCU.

- mavros/launch/apm.launch
Warning: You are using <arg> inside an <include> tag with the default=XY attribute - which is superfluous.
Use value=XY instead for less confusion.
Attribute name: respawn_mavros
> apm.launch: Avoid warning:

- libmavconn/include/mavconn/udp.h
- libmavconn/src/udp.cpp
- mavros/src/lib/mavros.cpp
Hi all! Are you still open for PRs on the ROS 1 version of mavros?
I wanted to get the IP of the ground control station that mavros/mavconn connects to, so I made this change. I'm not sure if this is something you want in the upstream mavros, but I'm making this PR to find out.
It runs a 1 Hz timer in the main mavros loop that checks the ip stored in the MAVConnUDP instance (through a new public const method), and publishes it on a latched topic `gcp_ip`. It only does this once.
This implementation works, but it feels like it could be integrated in a nicer way. All suggestions appreciated.
> Dispatch GCS IP address

- mavros/scripts/install_geographiclib_datasets.sh
Now script hasn't got error handler. Some time ago it was the problem with SourceForge mirrors. But this script didn't print any errors. And it was so difficult to understand, what the problem with dataset.
After path if dataset isn't downloaded, the script will write an error meaasge.
> Add error message in install_geographiclib_datasets.sh

- mavros/src/plugins/param.cpp
Solution to https://github.com/mavlink/mavros/issues/1461
- When loading parameters, store the parameter type
- When setting a parameter, check whether it is a known real-valued parameter. If so, use `0.0`.
Launch mavros and type the following in another terminal:
```
rosservice call /mavros/param/set "param_id: 'EKF2_EV_POS_X'
value:
integer: 0
real: 0.0"
```
In the current `master` branch in `mavros`, we see the following output:
```
[ INFO] [1598654552.748968591, 13.868000000]: FCU: [pm] param types mismatch param: EKF2_EV_POS_X
[ WARN] [1598654553.710428267, 14.828000000]: PR: Resend param set for EKF2_EV_POS_X, retries left 2
[ INFO] [1598654553.714391652, 14.832000000]: FCU: [pm] param types mismatch param: EKF2_EV_POS_X
[ WARN] [1598654554.712170340, 15.828000000]: PR: Resend param …
```
> Cannot set parameter to 0.0 using /mavros/param/set

- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/play_tune.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/PlayTuneV2.msg
Now that PX4 has proper handling of incoming PLAY_TUNE/PLAY_TUNE_V2 mavlink messages, I've written a tiny plugin that allows sending these tunes from ROS.
I've added a mavros_msgs/PlayTuneV2 for this, to make the interface clear, which includes the tune format and tune string.
Tested on a pixhawk with PX4 v1.11, and it plays as expected.
> play_tune: Write new plugin

- mavros_extras/src/plugins/fake_gps.cpp
This colon should probably be an equals sign.
With the colon, this assignment becomes a label instead,
and `_gps_rate` after the colon becomes an unused
expression result.
Glancing at the code, I suppose the result of this bug is that the default gps rate of 5 Hz was used always, even if the "gps_rate" node param was set to something else.
> fake_gps: Fix assignment typo

- mavros_extras/src/plugins/distance_sensor.cpp
Right now, if you get a distance sensor message from mavlink, and its orientation does not match the expected orientation (from your mavros config), the plugin prints an error but still publishes the data to ros, with the configured frame_id. It's probably better to not produce data when we know it's incorrect, so we suggest adding an early return to the relevant block.
> Don't publish distance sensor when orientation is wrong

- mavros/src/plugins/sys_status.cpp
- mavros_msgs/msg/VehicleInfo.msg
Hi! I thought it might be useful to some to include the custom firmware version info in the vehicle info. This adds a string type field `flight_custom_version` to the VehicleInfo message, which corresponds to the field of the same name in MAVLink [AUTOPILOT_VERSION](https://mavlink.io/en/messages/common.html#AUTOPILOT_VERSION). Then it takes the custom version from the autopilot, which is an array of 8 bytes, converts it to hex string with the existing method, and sends it.
> Report custom firmware version

- libmavconn/test/test_mavconn.cpp
- mavros/include/mavros/setpoint_mixin.h
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/hil.cpp
- mavros/src/plugins/manual_control.cpp
- mavros/src/plugins/rc_io.cpp
- mavros/src/plugins/safety_area.cpp
- mavros/src/plugins/sys_status.cpp
- mavros/test/test_frame_conversions.cpp
- mavros_extras/src/plugins/distance_sensor.cpp
- mavros_extras/src/plugins/gps_rtk.cpp
- mavros_extras/src/plugins/log_transfer.cpp
- mavros_extras/src/plugins/mocap_pose_estimate.cpp
- mavros_extras/src/plugins/px4flow.cpp
Uninitialised Mavlink 2 extension fields were sent if the fields were not later set to a value. Initialising the fields to zero is the default value for Mavlink 2 extension fields and appears to the receiver as though sender is unaware of Mavlink 2.
Messages affected by Mavlink 2 extensions found uninitialised:
DISTANCE_SENSOR
SET_GPS_ORIGIN
HIL_GPS
HIL_SENSOR
RC_CHANNELS_OVERRIDE
ATT_POS_MOCAP
Examples here were found with a regex. Further examples may exist of this bug.
Additionally fixes some tests for upstream and in-package changes
> Add message struct initialisations

- mavros_extras/src/plugins/odom.cpp
Add missing estimator_type field in  Odometry message.
Issue #1524
> bugfix - add estimator type in odom message

- mavros_extras/src/plugins/odom.cpp
Fixed a bug in mavros_extras/src/plugins/odom.cpp by switching lines 175 and 180
Rationale: The pose covariance matrix published to the /mavros/odometry/in topic is exclusively zeros. This is because the transformation matrix r_pose is initialised as zeros (line 140), then applied to the covariance matrix cov_pose (line 176) and then populated (line 180). Clearly the latter two steps should be the other way around, and the comments in the code appear to suggest that this was the intention, but that lines 175 and 180 were accidentally written the wrong way around. Having switched them, the pose covariance is now published to /mavros/odometry/in as expected.
JohnG897
> Fixed a bug in mavros_extras/src/plugins/odom.cpp by switching lines 175 and 180

- mavros/include/mavros/frame_tf.h
- mavros/src/lib/ftf_frame_conversions.cpp
- mavros/src/plugins/setpoint_position.cpp
- mavros/src/plugins/setpoint_raw.cpp
When sending yaw in BODY_NED frame using setponit_raw,  not only is there a 90° offset but the direction is also reversed.
When sending yaw in BODY_NED frame using setponit_position,  the direction is reversed.
The yaw is supposed to follow the 'FLU' convention in ROS, thus, a positive angle would be from F to L(anticlockwise).
The changes made should fix both problems.
They were both tested and worked as expected.
> fixed yaw problems in setponit_raw and setponit_position when using BODY_NED and BODY_OFFSET_NED

- mavros/README.md
This is intended as a cleanup commit, and only contains changes to the MAVROS README.md file, nothing major.
My intention is to make sure some of the projects are named correctly throughout the file, and also update the outdated project descriptions for the PX4 Autopilot, QGroundControl, and MAVLink. 
cc @LorenzMeier (since you did the last round of updates in 2016)
> README: Update PX4 Autopilot references

- mavros/CMakeLists.txt
- mavros/include/mavros/mission_protocol_base.h
- mavros/mavros_plugins.xml
- mavros/src/plugins/geofence.cpp
- mavros/src/plugins/mission_protocol_base.cpp
- mavros/src/plugins/rallypoint.cpp
- mavros/src/plugins/waypoint.cpp
For #1157. Breaks out the mission protocol into a base class from the waypoint plugin and adds the ability to send rallypoints and geofences
> Send rallypoints and geofences through mavros

- mavros/launch/px4_config.yaml
- mavros_extras/src/plugins/distance_sensor.cpp
Currently, the `distance_sensor` plugin does not fill the `horizontal_fov`, `vertical_fov` and `quaternion` fields of the [`DISTANCE_SENSOR`](https://mavlink.io/en/messages/common.html#DISTANCE_SENSOR) message. This results in uninitialized values being sent to the flight controller.
This P/R fills in the `horizontal_fov` and `vertical_fov` fields from the `field_of_view` field of the `sensor_msgs/Range` message. It also sets the quaternion to zero (it is not used unless the orientation is set to `MAV_SENSOR_ROTATION_CUSTOM`, and the message description says: "Set it to 0 if invalid.").
> distance_sensor: Fill horizontal_fov, vertical_fov, quaternion

- mavros/CMakeLists.txt
- mavros/include/mavros/mavros_router.hpp
- mavros/include/mavros/mavros_uas.hpp
- mavros/include/mavros/plugin.hpp
- mavros/include/mavros/px4_custom_mode.hpp
- mavros/include/mavros/setpoint_mixin.hpp
- mavros/src/lib/enum_to_string.cpp
- mavros/src/lib/uas_ap.cpp
- mavros/src/lib/uas_stringify.cpp
- mavros/src/plugins/ftp.cpp
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/imu.cpp
- mavros/src/plugins/param.cpp
- mavros/src/plugins/rc_io.cpp
- mavros/src/plugins/setpoint_raw.cpp
- mavros/src/plugins/sys_status.cpp
- mavros_cog.py
- mavros_extras/CMakeLists.txt
- mavros_extras/src/plugins/landing_target.cpp
(This PR also contains the work from https://github.com/mavlink/mavros/pull/1603, so make sure to merge that first :))
It's not 100% tested yet. Planning on testing raw landing target input with this as soon as I have a good source for landing targets and their tfs in ros2.
I am publishing this PR as it ported parts of the `TF2ListenerMixin` which might be helpful elsewhere.
```
$ colcon build --packages-up-to mavros_extras
Starting >>> libmavconn
Starting >>> mavros_msgs
Finished <<< libmavconn [0.40s]                                                             
Finished <<< mavros_msgs [12.0s]                     
Starting >>> mavros   
Finished <<< mavros [1.56s]                      
Starting >>> mavros_extras
Finished <<< mavros_extras [0.79s]                      
Summary: 4 …
```
> mavros_extras: Ported landing target plugin to ROS2

- libmavconn/src/tcp.cpp
- mavros/src/gcs_bridge.cpp
When a client suddenly drops the connection,
socket.shutdown() will throw an exception:
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
what():  shutdown: Transport endpoint is not connected
Showing an error in this common case looks more reasonable than crashing.
> Show ENOTCONN error instead of crash on socket's shutdown

- mavros_extras/src/plugins/distance_sensor.cpp
I noticed an issue where distance sensor data I send via from a ROS system via MAVROS to an autopilot gets invalid quaternion values. This turned out to be caused by the (Eigen) quaternion orientation not being initialized in the distance_sensor plugin, so if the default quaternion orientation is used, it's values will be random garbage data.
This is because the default constructor for an Eigen quaternion doesn't initialize it.
Here's an example of `listener distance_sensor` output from PX4 before this fix:
```
Instance 2:
distance_sensor_s
timestamp: 77083719  (0.030450 seconds ago)
min_distance: 0.1000
max_distance: 100.0000
current_distance: 1.6700
variance: 0.0000
h_fov: 0.0872
v_fov: 0.0872
q: [70931685123886100000000.0000, 18058769791168100000000000000.0000, 51190050062336.0000, …
```
> distance_sensor: Initialize sensor orientation quaternion to zero

- mavros/launch/px4_config.yaml
- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/camera.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/CameraImageCaptured.msg
**Problem Description**
This PR adds a camera plugin, which captures the `CAMERA_IMAGE_CAPTURED` message which contains viewpoint information when an image is triggered. This information is very useful for robotic applications involving viewpoint tracking.
This is different from the camera trigger messages coming from `cam_imu_sync`, which is used to sync camera and imu timing since this is related to the actual mavlink camera protocol: https://mavlink.io/en/services/camera.html
**Testing**
Tested with PX4 Software-In-The-Loop Gazebo simulation with camera enabled vehicles such as `plane_cam`
**Additional Context**
- We may further extend this to comply with the mavlink protocol, but not sure if there is a good enough general camera framework in ROS that is worth integrating into
> Add camera plugin for interfacing with mavlink camera protocol

- libmavconn/include/mavconn/interface.h
- libmavconn/include/mavconn/serial.h
- libmavconn/include/mavconn/tcp.h
- libmavconn/include/mavconn/udp.h
- libmavconn/src/interface.cpp
- libmavconn/src/serial.cpp
- libmavconn/src/tcp.cpp
- libmavconn/src/udp.cpp
- libmavconn/test/test_hang.cpp
- libmavconn/test/test_mavconn.cpp
- mavros/src/gcs_bridge.cpp
- fix bad_weak_ptr on connect and disconnect
- introduce new API to avoid thread race when assigning callbacks
- fix uninitialized variable in TCP client constructor which would
randomly block TCP server
This is an API breaking change: if client code creates connections using
make_shared<>() instead of open_url(), it is now necessary to call new
connect() method explicitly.
Related:                                                                                                                                                                                       
https://github.com/mavlink/mavros/issues/1597 …
> Fix multiple bugs

- mavros/include/mavros/mission_protocol_base.h
- mavros/src/lib/mavros.cpp
- mavros/src/plugins/ftp.cpp
- mavros/src/plugins/geofence.cpp
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/param.cpp
- mavros/src/plugins/rallypoint.cpp
- mavros/src/plugins/setpoint_attitude.cpp
- mavros/src/plugins/setpoint_position.cpp
- mavros/src/plugins/setpoint_trajectory.cpp
- mavros/src/plugins/sys_status.cpp
- mavros/src/plugins/sys_time.cpp
- mavros/src/plugins/waypoint.cpp
- mavros_extras/src/plugins/distance_sensor.cpp
- mavros_extras/src/plugins/gps_input.cpp
I have some build warnings in the mavros and mavros_extras packages when I build locally with Clang, which I've attempted to fix.
I think some of these changes are uncontroversial, such as
* reordering constructor initializer lists to avoid "-Wreorder-ctor",
* initializing yaw and yaw_rate explicitly to zero in the setpoint_trajectory plugin, and
* fixing the probably incorrect gps_rate initialization.
There was also a warning where `MissionBase::initialize(ros::NodeHandle *_wp_nh)` upsets the compiler because it "hides the overloaded virtual function `PluginBase::initialize(UAS &uas)` because MissionBase inherits from PluginBase. I've avoided this by renaming `MissionBase::initialize` but you may want to solve it differently, or give it a different name.
After this, all that remains when …
> Fix warnings

- mavros/src/lib/mavros_uas.cpp
This bug caused mavros to crash randomly. Is there maybe a check that can be enabled in g++ to catch these kind of bugs?
Rationale:
For basic types, fields get initialized with there default value, but struct types get garbled memory, unless passed an initializer list.
See also: https://en.cppreference.com/w/cpp/language/default_initialization
> Fix spurious bug because class field was uninitialized.

- mavros/src/plugins/sys_time.cpp
Problem: parameter `time/publish_sim_time = true` pretty much breaks the simulation.
As I understand using `getParam` without checking the return value keeps `publish_sim_time` variable random. So `param` with the default value must be used here.
> Set time/publish_sim_time to false by default

- libmavconn/src/tcp.cpp
MavconnTCPClient: When calling the `close()` function (by a different thread), a mutex is taken at
the start of this function which closes the socket and waits the end of io_service thread.
Closing the socket causes the `Operation aborted` error in `do_recv()` function called by
io_service thread which in turn calls the `close()` function.
This causes a 'deadlock'.
fix: Reduce the scope of the mutex in the `close()` function so that it is released before
waiting the end of io_service thread.
> libmavconn: fix deadlock when call close()

- libmavconn/include/mavconn/tcp.hpp
- libmavconn/src/tcp.cpp
When the tcp connection is lost (remote TCP server stopped), an `End of file` error is caught
by the `io_thread` in the `do_recv()` that calls the `close()` function.
In the `close()` function, we stop the io_service and wait the end of the io_thread which
causes an `std::system_error exception` _(cause: Resource deadlock avoided)_.
```
Error:   mavconn: tcp0: receive: End of file at line 250 in libmavconn/src/tcp.cpp
terminate called after throwing an instance of 'std::system_error'
what():  Resource deadlock avoided
Aborted (core dumped)
```
fix:
- close() function: stop io_service if current thread id != io_thread id
- ~MAVConnTCPClient(): stop io_service and io_thread if thread is running
> fix std::system_error when tcp interface loses connection

- mavros/launch/px4_config.yaml
I guess this feature is not needed any more. 
Moreover it breaks connection with the most recent PX4 build, as it autostarts either MAVLink or shell on USB based on traffic it sees.
> Disable startup_px4_usb_quirk in px4_config.yaml

- mavros_extras/src/plugins/obstacle_distance.cpp
Hi!
This PR contains two bugfix in the /mavros_extras/src/plugins/obstacle_distance.cpp file.
**The first one** corrects the way the reduction of size of the LaserScan is done. 
The code should redux the resolution of the array to adjust to the mavlink OBSTACLE_DISTANCE message (72 values) taking the minimum value as aggregation function of the interpolation.
The scale_factor was taken as integer, so the interpolation worked wrong.
This image shows the error and the fix:
**The second bugfix** assigns a value to increment_f in case the size of the input LaserScan is bigger than the mavlink OBSTACLE_DISTANCE message.
This was missing, so ardupilot was usgin the value of increment (and NOT increment_f), showing wrong objects.
> Fix obstacle distance

- mavros/src/plugins/sys_status.cpp
This message has been deprecated
> sys_status.cpp: remove deprecated BATTERY2 mavlink message support

- mavros/src/plugins/sys_status.cpp
Do not use battery1 voltage as voltage for all other batteries (bugfix).
Support both cell and total voltages above 65V
Support up-to 14S batteries
If available, add cell voltage information to the battery diagnostic
Tested on a drone with 3 batteries, and multiple cells
> sys_status.cpp: Do not use battery1 voltage for all batteries.

- mavros/src/plugins/command.cpp
- mavros/src/plugins/sys_status.cpp
Tentative fix for #1588 
Adding the timer to the `srv_cg` callback group appears to resolve the issue. Not entirely sure why that is. Potentially rclcpp/rmw internals causing a deadlock.
> Maybe fix sys status callbacks

- libmavconn/include/mavconn/udp.hpp
- libmavconn/src/udp.cpp
Same problems as for the TCP:
- #1682: fix std::system_error when tcp interface loses connection
- #1679: fix deadlock when call close()
> libmavconn: fix UDP deadlocks

- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/cellular_status.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/CellularStatus.msg
This addition allows the onboard computer (OBC) to send the MAVlink message [Celular status](https://mavlink.io/en/messages/common.html#CELLULAR_STATUS) via ROS.
It's used when the OBC has a cellular connection and it's reported to the ground station or any other components compatible with MAVlink.
> Pr cellular status

- mavros_extras/src/plugins/vision_pose_estimate.cpp
Fixes #1734 
I removed the call to the `RCLCPP_INFO_STREAM`: it didn't seem to belong in this routine. If there's a reason to keep it perhaps it should be `ONCE` or `DEBUG`.
> Fix crash in vision_pose plugin

- mavros/launch/apm_config.yaml
- mavros/launch/px4_config.yaml
- mavros_extras/src/plugins/mount_control.cpp
fix pitch sign
correct MountConfigure response success
> mount_control.cpp: detect MOUNT_ORIENTATION stale messages

- mavros/mavros/cmd/checkid.py
In that PR, the attribute name is changed to msgname due to conflicts with message instance variables.
The version number in the comment needs to be updated once <https://github.com/ArduPilot/pymavlink/pull/664> is merged and released.
> Make compatible with pymavlink type annotations PR

- mavros/mavros/cmd/checkid.py
Now that the change has been merged into master in pymavlink,
it will be in the next tagged release.
This change should also not introduce any linter errors this time...
> Put correct version in comment

- mavros/launch/apm_config.yaml
- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/guided_target.cpp
This PR attempts to implement the suggestions in the PR #1184 by @rmackay9 to allow mavros to accept [POSITION_TARGET_GLOBAL_INT](https://mavlink.io/en/messages/common.html#POSITION_TARGET_GLOBAL_INT) message from FCU or GCS.
There were suggestions by @TSC21 and @vooon to implement a separate plugin for the purpose and use POSITION_TARGET_GLOBAL_INT message type.
There's an issue I found:
- After commanding the vehicle in off-board mode to a specific location, vehicle tends to go to a specific position(different from what it is commanded) everytime.
Hoping for a resolution to this issue.
> guided_target: accept position-target-global-int messages

- libmavconn/include/mavconn/interface.h
- libmavconn/src/interface.cpp
> libmavconn: fix MAVLink v1.0 output selection

- mavros_extras/src/plugins/guided_target.cpp
I stumbled upon what I think is a bug here, thanks to a `-Wparentheses` warning I got (clang 13, but I'm guessing this is on gcc too).
The warning text explains:
> & has lower precedence than >; > will be evaluated first
which I don't think is what we want here. The if statement will evaluate to false in some cases where it shouldn't, such as when:
* `type_mask` is 2 = 0b0010
* `IGNORE_LATITUDE` is 1 = 0b0001
* `IGNORE_LONGITUDE` is 2 = 0b0010
then the if statement evaluates to
* `0b0010 & (0b0001 | 0b0010)  > 0`
* `0b0010 & 0b0011 > 0`
* `0b0010 & true` because > evaluates first
* `0b0010 & 0b0001`
* `0b0000`
* `false`
which is wrong!
We can fix this by adding parentheses:
```cpp
if ((position_target.type_mask & (mavros_msgs::GlobalPositionTarget::IGNORE_LATITUDE | …
```
> mavros_extras: Fix buggy check for lat/lon ignored

- mavros_extras/src/visualization.cpp
This line triggers a `-Wsequence-point` warning. You can read about it here: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
It seems to be that doing `++` (which modifies a variable) and assigning the result back to the same variable can be undefined behaviour.
In this case, we don't need to pre-increment, we can just add one, and then save the result back to the variable. This makes the warning go away, and seems to make sense.
> mavros_extras: Fix a sequence point warning

- mavros_extras/src/plugins/guided_target.cpp
Hi all, I think this is a bug. This expression is written with a bitwise OR `|`, but it seems like it should have been written with a logical OR `||`.
> mavros_extras: Fix a comparison that shouldn't be bitwise

- mavros/include/mavros/mission_protocol_base.h
- mavros/src/plugins/dummy.cpp
- mavros/src/plugins/sys_status.cpp
- mavros/src/plugins/sys_time.cpp
This introduces no functional change, but gets rid of a few `-Wsign-compare` warnings and one `-Wformat-pedantic` warning.
> mavros: Fix some warnings

- mavros_extras/src/plugins/debug_value.cpp
- mavros_msgs/msg/DebugValue.msg
Implements the debug float array which was previously not implemented.
We chose to use the debug float array name to match https://github.com/mavlink/mavlink/pull/734 
Tested in flight and works.
> Implement debug float array handler

- mavros/src/plugins/global_position.cpp
Sometimes when a subscriber subs to "gp_origin" topic it doesn't receive a message in time leading to race conditions. Made it such that the publisher is latched so subscribers always gets the gp_origin on demand.
> Made it such that the gp_origin topic publisher is latched.

- mavros/src/plugins/ftp.cpp
df4e529 mistakenly switched `PayloadHeader::data` from using a non-standards compliant (but accepted by most compilers) flexible array to a pointer. This resulted in an attempt to dereference the uninitialized contents of the array.
This patch eliminates `PayloadHeader::data` and instead makes `FTPRequest::data()` use pointer arithmetic to get the data buffer from within the payload buffer.
This fixes the crash, but the plugin still doesn't work quite right, at least with ArduPilot. The only command I have been able to execute successfully is checksum.
Fixes #1695
> plugins: ftp: fix null pointer dereference

- mavros/launch/apm.launch
- mavros/launch/apm_pluginlists.yaml
- mavros/launch/node.launch
If these changes are not made, there are several errors when trying to launch `apm.launch` . ROS2 Foxy.
1. error:
```
[ERROR] [mavros_node-1]: process has died [pid 59547, exit code -6, cmd '/home/dcs_user/ros2_ws/install/mavros/lib/mavros/mavros_node --ros-args -r __ns:=/mavros --params-file /tmp/launch_params_u3s_gn73 --params-file /tmp/launch_params_l0ol9u7q --params-file /tmp/launch_params_9v2uyjt4 --params-file /tmp/launch_params_p_qmy_03 --params-file /tmp/launch_params_pslty43k --params-file /home/dcs_user/ros2_ws/install/mavros/share/mavros/launch/apm_pluginlists.yaml --params-file /home/dcs_user/ros2_ws/install/mavros/share/mavros/launch/apm_config.yaml'].
```
2. error:
```
ValueError: $(var log_output) is not a valid standard output config i.e. "screen", "log" or "both"
``` …
> Fix apm_pluginlist.yaml and apm.launch

- mavros/launch/apm_config.yaml
- mavros/launch/apm_pluginlists.yaml
- mavros/launch/px4_config.yaml
- mavros/launch/px4_pluginlists.yaml
1. The plugin denylist allowlist `plugin_allowlist` and `plugin_denylist`.
2. When change the node's namespace, the plugin parameters cannot be loaded normally.
The parameter file needs to fit into the namespace.
Like this：
```
/mavros/**:
ros__parameters:
startup_px4_usb_quirk: false
/mavros/**/conn:
ros__parameters:
heartbeat_rate: 1.0    # send heartbeat rate in Hertz
heartbeat_mav_type: "ONBOARD_CONTROLLER"
```
Use `/**` to fit the new namespace.
It can alse fit the default namespace `mavros`.
> fix ROS2 launch parameters namespace and name.

- mavros/mavros/mavlink.py
- test_mavros/scripts/test_mavlink_convert_to_rosmsg.py
> cast payload_octest to int

- libmavconn/CMakeLists.txt
- mavros/CMakeLists.txt
- mavros/include/mavros/mavlink_diag.h
- mavros/src/lib/mavlink_diag.cpp
- mavros_extras/CMakeLists.txt
- mavros_extras/src/plugins/landing_target.cpp
- mavros_extras/src/plugins/mount_control.cpp
- mavros_extras/src/plugins/wheel_odometry.cpp
- test_mavros/CMakeLists.txt
Hi all, this does three things:
* Use the [cmake SYSTEM option](https://cmake.org/cmake/help/latest/command/include_directories.html) to have it consider 3rd party library headers as system headers, and thus not emit build warnings from them.
* Fix some build warnings in mavros_extras.
* Remove unneeded trailing semicolon on some namespace declarations.
Feel free to use this if it's useful for you.
> Fix / suppress some build warnings

- mavros_extras/CMakeLists.txt
- mavros_extras/mavros_plugins.xml
- mavros_extras/src/plugins/optical_flow.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/OpticalFlow.msg
This PR proposes the addition of a new OpticalFlow.msg file to enhance the [optical flow](https://mavlink.io/en/messages/common.html#OPTICAL_FLOW) support in MAVROS
> Addition of New OpticalFlow.msg

- mavros_extras/src/plugins/gps_status.cpp
Filled in available fields in [GPS_RAW_INT](https://mavlink.io/en/messages/common.html#GPS_RAW_INT) & [GPS2_RAW](https://mavlink.io/en/messages/common.html#GPS2_RAW) messages for ROS1
p.s. seems GPS2_RAW more complete than original GPS_RAW_INT
> GPS_STATUS: Fill in available messages for ROS1 legacy

- mavros_extras/src/plugins/guided_target.cpp
I stumbled upon a variable that does not seem to be used anywhere in the file. And since it's a private variable it won't be used anywhere else outside the class.
> Removed unused variable

- mavros_extras/src/plugins/camera.cpp
Both `image_index` and `capture_result` fields of the `mavros_msgs::CameraImageCaptured` were left unassigned.
Assign the proper values to them according to the `CAMERA_IMAGE_CAPTURED` message
> [camera plugin] Fix image_index and capture_result not properly filled

- mavros/src/plugins/sys_status.cpp
- mavros_msgs/CMakeLists.txt
- mavros_msgs/msg/StatusEvent.msg
Hello all, working with PX4 we are starting to use EVENT instead of STATUS_TEXT for more details over the status of the autopilot. For this we needed to have the EVENT messages bridged to ROS2. This is my implementation, taking input from other people to have it merged in upstream mavros
> Add support for EVENT messages 

- mavros/src/lib/uas_tf.cpp
- mavros/src/plugins/global_position.cpp
- mavros/src/plugins/home_position.cpp
- mavros/src/plugins/imu.cpp
- mavros/src/plugins/local_position.cpp
Recently I removed some obsolete headers from geometry2 https://github.com/ros2/geometry2/pull/645. This PR update the code to fix the warning and the buildfarm https://build.ros2.org/view/Rbin_uJ64/job/Rbin_uJ64__mavros__ubuntu_jammy_amd64__binary/257/console
> Removed warning from geometry2 header

- mavros/launch/apm_config.yaml
- mavros/launch/px4_config.yaml
move /conn parameters to /sys and /time to fix #1930
> fix issue #1930

- mavros/mavros/mavlink.py
The None in the signing field (bug #569) made the code throw exceptions while decoding. There is still no signing support, but the empty array is working better than the None value. Fixed another bug in the building of the ROS Mavlink message- the seq field was not added to the ROS Mavlink message, causing a CRC error while decoding the message.
> Bug fixes in translating from Mavlink to ROS-Mavlink

- mavros_extras/src/plugins/mag_calibration_status.cpp
The error is:
src/plugins/mag_calibration_status.cpp:64:22: error: ‘bitset’ is not a member of ‘std’
> Fix compile error when compiling with gcc 13

- mavros/include/mavros/mavros_uas.hpp
- mavros/setup.cfg
Building mavros (ubuntu 22.04 ros2 humble) fails due to deprecation warnings treated as errors.
> fix depcrecation errors

- mavros_extras/CMakeLists.txt
- mavros_extras/package.xml
Solves std_srvs/Trigger.h not found when compiling log_transfer.cpp.
> Add missing std_srvs dependency

- mavros_extras/CMakeLists.txt
This PR addresses the pre-Jazzy build error introduced in #1988, where `yaml-cpp` cannot be found. I've done some testing to verify that things build and run as expected using ROS 2 Humble, Iron, Jazzy, and Rolling.
- Fixes #1989
> Resolve build error when linking yaml-cpp

- README.md
As promised, here is the updated README, which includes the build statuses for the latest Jazzy and Rolling releases. It doesn't appear as though the badges are available for these releases yet, but folks should still be able to determine that the binaries are available.
(marking these two issues as fixed - I can remove these if you'd prefer to manually close them)
- Fixes #1960
- Fixes #1958
> Update build list in README

- mavros/src/lib/ftf_frame_conversions.cpp
- mavros/test/test_frame_conversions.cpp
The template specializations of `transform_static_frame()` and `transform_frame()` for the type `Covariance3d` improperly rotate the covariance matrix.
**Old (broken) implementation**
The old implementation is wrong and returns an ill-conditioned covariance matrix, breaking symmetry and positive-semi-definitiveness.
Taking for example the following covariance matrix `P`  and quaternion `q`:
```
| 0.1 0.2 0.3 |
P = | 0.2 0.4 0.5 |
| 0.3 0.5 0.6 |
q = 1i + 0j + 0k + 0  # 180deg around X
```
The old implementation would return the matrix `P'`:
```
| 0.1 -0.2 -0.3 |
P' = P * q = P * R(q) = | 0.2 -0.4 -0.5 |
| 0.3 -0.5 -0.6 |
```
which is clearly invalid (asymmetric and negative).
**New (proper) implementation**
The new implementation correctly rotates the 3x3 covariance matrix by left- and …
> Fix 3x3 covariance matrix rotation/transformation

- README.md
This pull request updates the MAVROS documentation links from the master branch to the ros2 branch for the following references:
[mrrm]: Updated to point to ros2/mavros/README.md
[exrm]: Updated to point to ros2/mavros_extras/README.md
[libmc]: Updated to point to ros2/libmavconn/README.md
[test]: Updated to point to ros2/test_mavros/README.md
[inst]: Updated to point to ros2/mavros/README.md#installation
The references [geolib] and [iss1369] remain unchanged as they point to external sources and open issues, respectively.
This change ensures the documentation reflects the current ROS2 development branch and prevents confusion when navigating the project.
Note: No functional code changes are included in this PR, only documentation link updates.
> Update MAVROS ROS2 Documentation Links to their respective ROS2 Branch Links

- mavros_extras/src/plugins/landing_target.cpp
This change implements a check to support the set landing target frame of reference when using the "~/landing_target/raw" interface. 
* The transformations for the `MAV_FRAME::LOCAL_NED` case are the same as the previous implementation
* The transformations for the `MAV_FRAME::BODY_FRD` case have been derived by myself, and seem to work as expected under my testing. A cross-check is probably a good idea. 
One issue with this commit is in regards to handling the case where a use does not want to use the position data at all, and in doing so, is likely to not set the frame parameter. It is expected that this would result in a value of "0" being set, which aligns to MAV_FRAME::GLOBAL. This is not a valid setting for any autopilots I'm aware of, so I've used this is a selector for whether to …
> Support specified frames of reference in landing target module

- mavros/include/mavros/mavros_router.hpp
- mavros/include/mavros/plugin.hpp
RCLCPP_SMART_PTR_DEFINITIONS eventually is expanding to:
\#define __RCLCPP_MAKE_UNIQUE_DEFINITION(...) \
template<typename ... Args> \
static std::unique_ptr<__VA_ARGS__> \
make_unique(Args && ... args) \
{ \
return std::unique_ptr<__VA_ARGS__>(new __VA_ARGS__(std::forward<Args>(args) ...)); \
}
which is incorrect for abstract classes like Endpoint or Plugin
RCLCPP_SMART_PTR_DEFINITIONS_NOT_COPYABLE is used instead excluding make_unique functionality
This allows to use clang compiler to build mavros
> Fix incorrect macro usage
